sonar.organization=arkrix
sonar.projectKey=arkrix_vylop
sonar.projectName=vylop

# Source and Test Directories
sonar.sources=server/src/main/java,web/src
sonar.tests=server/src/test/java

sonar.sourceEncoding=UTF-8
sonar.java.binaries=server/target/classes

# Exclude all frontend components and static assets from duplication & coverage calculations
sonar.coverage.exclusions=web/**,**/*.css,**/*.scss,**/*.test.*,**/*.spec.*
sonar.cpd.exclusions=web/**
sonar.exclusions=web/dist/**,web/build/**,web/node_modules/**,server/target/**